version: '3'

services:
  app:
    image: node:18
    container_name: app
    networks:
      - nodenetwork
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "cd /usr/src/app && npm init -y && npm install express mysql2 faker@5.5.3 && chmod +x wait-for-it.sh && ./wait-for-it.sh -t 15 db:3306 -- node index.js"
    
  db:
    image: mysql:8.1
    command: --innodb-use-native-aio=0 && bash -c "sleep 10 && mysql -h db -u root -proot < /docker-entrypoint-initdb.d/init.sql"
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenetwork

  nginx:
    build:
      context: nginx
    ports:
      - "8080:80"  
    volumes:
      - ./nginx:/etc/nginx/conf.d 
    depends_on:
      - app 
    networks:
      - nodenetwork
     

networks:
  nodenetwork:
    driver: bridge